git mv APP.scss ../../stylesheets
git mv AddColorForm.scss ../../stylesheets
git mv Color.scss ../../stylesheets
git mv ColorDetails.scss ../../stylesheets
git mv ColorList.scss ../../stylesheets
git mv FilePicker.scss ../../stylesheets
git mv LinksQaResultsComponent.scss ../../stylesheets
git mv LinksQaRunForm.scss ../../stylesheets
git mv Menu.scss ../../stylesheets
git mv ObjectivesFilterForm.scss ../../stylesheets
git mv ObjectivesListComponent.scss ../../stylesheets
git mv Star.scss ../../stylesheets
git mv globals.scss ../../stylesheets
