const constants = {
    OBJECTIVES_GET: 'OBJECTIVES_GET',
    OBJECTIVES_FETCHING: 'OBJECTIVES_FETCHING',

    USERS_GET: 'USERS_GET',
    USERS_FETCHING: 'USERS_FETCHING',

    USER_SET_PASSWORD_HASH: 'USER_SET_PASSWORD_HASH',

    USER_LOGIN: 'USER_LOGIN',
}

export default constants
