const constants = {
    OBJECTIVES_GET: 'OBJECTIVES_GET',
    OBJECTIVES_FETCHING: 'OBJECTIVES_FETCHING',

    USERS_GET: 'USERS_GET',
    USERS_FETCHING: 'USERS_FETCHING',
}

export default constants
