const constants = {
    ADD_COLOR: "ADD_COLOR",
    RATE_COLOR: "RATE_COLOR",
    REMOVE_COLOR: "REMOVE_COLOR",
    LINKS_QA_RUN: "LINKS_QA_RUN",
    OBJECTIVES_GET: "OBJECTIVES_GET",
    OBJECTIVES_LOADING: "OBJECTIVES_LOADING"
}

export default constants
