REM unauthorized...username 'arnie' does not exist...
REM curl -v --noproxy localhost --trace-ascii curl-login-user.trace-ascii.out -H "Content-Type: application/json" -XPOST --data "{\"username\":\"arnie\", \"password\":\"pass\"}" "http://localhost:3004/scrumi-react/user_login_session_api"
REM unauthorized...bad password for 'matrix'...
curl -v --noproxy localhost --trace-ascii curl-login-user.trace-ascii.out -H "Content-Type: application/json" -XPOST --data "{\"username\":\"matrix\", \"password\":\"passé\"}" "http://localhost:3004/scrumi-react/user_login_session_api"
REM good password for 'matrix'...
REM curl -v --noproxy localhost --trace-ascii curl-login-user.trace-ascii.out -H "Content-Type: application/json" -XPOST --data "{\"username\":\"matrix\", \"password\":\"pass\"}" "http://localhost:3004/scrumi-react/user_login_session_api"
